# Generated by Django 4.1.4 on 2022-12-12 22:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='products/%Y/%m/%d/')),
                ('formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('InStock', 'В наличии'), ('UnderTheOrder', 'Под заказ'), ('ExpectedReceipt', 'Ожидается поступление'), ('OutOfStock', 'Нет в наличии'), ('NotProduced', 'Не производится')], max_length=20)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.image')),
            ],
        ),
    ]
